- name: Install prerequisites
  become: yes
  hosts: all
  vars:
    applications:
      - openjdk-11-jdk
      - curl
      - maven
  tasks:
    - name: Install the application which are present
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - "{{ applications }}"
