apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: todo-app
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: root
  MONGO_ROOT_PASSWORD: password
  MONGO_URI: "mongodb://root:password@todo-mongo-service:27017/todo?authSource=admin"
