FROM node:16-bullseye-slim

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

ARG REACT_APP_BACKEND_SERVER_URL
ENV REACT_APP_BACKEND_SERVER_URL=$REACT_APP_BACKEND_SERVER_URL

EXPOSE 3000

CMD ["npm", "start"]
